### ISSUE TITLE
요약 보고서

### ISSUE THREAD

**Issue by kjlee342** [kookmin-sw/2018-cap1-8#1]
요약 보고서 PDF 준비.

양식
https://docs.google.com/document/d/1gDJahPv1WUIqw_W303ykcefYjTo1RJMU_7LcynZ__CU/edit?usp=sharing

**Comment by tttuer** [comment]
요약 PDF 작성완료

**Comment by tttuer** [comment]
요약 보고서 학번도 추가 완료
