### ISSUE TITLE
np.empty()의 함수에 관한 의문

### ISSUE THREAD

**Issue by tttuer** [kookmin-sw/2018-cap1-8#10]
cross_vali_data_convert_merge.py 파일에서 공식 홈페이지를 찾아보니 np.empty()를 적용하면 random 값이 각각의 값으로 들어가게 된다고 나와있는데 저희의 소스를 실행시켜보면 값이 들어가 있지 않은 비어있는 테이블이 생성된다고 나옵니다. 어떤점에서 이렇게 다른 값이 나오는지 궁금합니다.

**Comment by kjlee342** [comment]
보신 사이트가 잘 못 된 것 같습니다.

저도 사용해본 결과 미리 배열의 크기를 선언하는게 맞는 것 같습니다.
