### ISSUE TITLE
reshape(len(xx),-1)에서 -1이 무슨 효과인가요?

### ISSUE THREAD

**Issue by kjlee342** [kookmin-sw/2018-cap1-8#11]
cross_vail_data_convert_merge.py 파일 32번째 줄의 xx.reshape(len(xx),-1)을 쓰는데
reshape의 파라미터가 차원을 뜻하는 걸로 아는데 -1이 들어가면 어떻게 되는건지 잘 모르겠네요.

**Comment by tttuer** [comment]
len(xx)에 해당하는 길이로 행(x)을 할당을 해 주고, 나머지 값에 대해서는 그 차원에 해당하지 않는 차원에 할당을 해주는 역할을 합니다.
