### ISSUE TITLE
.csv 변경 코드에서 np.dstack시 .T의 의미?

### ISSUE THREAD

**Issue by bear1704** [kookmin-sw/2018-cap1-8#12]
27번째 라인 x = np.dstack(np.array(tmp1[k:k+window_size, 1:91]).T)에서,
T의 사용의미가 뭘까요?

**Comment by ec209** [comment]
T 는 matrix 를 transpose 시키는 것 입니다. 
transpose란 행과 열을 서로 교환 하는 것 입니다 
amplitude 데이터만 slicing하여 전치를 시키고 아래 코드를 보면 
timestamp
----------
amplitude

와 같은 구조로 vertically append를 하는것 같습니다

**Comment by kjlee342** [comment]
dstack시 .T가 없으면 90row 1000col이 되서 넣기 전에 transpose 해주는 것 같습니다.
