### ISSUE TITLE
cross_vali_data_convert_merge.py 에서 window_size 와 xx배열의 상관 관계

### ISSUE THREAD

**Issue by ec209** [kookmin-sw/2018-cap1-8#15]
window_size 를 바꿀 때 마다 xx배열이 어떻게 바뀌는가?

**Comment by kjlee342** [comment]
xx = np.empty([0,window_size,90],float)에서 xx는 window_size만큼의 행, 90개의 열을 가지며
배열의 층은 0으로 두어 특정한 값으로 정하지 않고 계속해서 늘어날 수 있도록 합니다.
후에 데이터가 입력되면 인풋 파일의 개수만큼 배열의 층이 쌓입니다.
