### ISSUE TITLE
모델 로딩과 예측 시간

### ISSUE THREAD

**Issue by kjlee342** [kookmin-sw/2018-cap1-8#24]
실시간 행동 인식을 위하여 저희 학습 모델을 불러오는 시간과

모델을 통하여 예측하는데 걸리는 시간을 재서 어떤 시간을 줄여야 할지 알고 방향을 정해야합니다.

그렇기 위해서 앞에서 말한 바와 같이 모델 로딩 시간과 예측 시간을 재주시기 바랍니다.

**Comment by ec209** [comment]
start_time 1525503460.467633
--- 374.200749874115 seconds --- // 모델을 이용하여 예측을 수행하기 전까지의 소요시간.
180505-160354
[[ 1.46805108 -0.27150142 -0.30625582 -0.36455423  0.7025426  -1.59529805
   1.10678232]]
[0]
start_time2 1525503834.668424
--- 5.167734146118164 seconds --- // 예측을 하는데 걸린 소요시간.
180505-160359

결론: 모델파일을 로딩하는데 374초가 소요 되었고, 실제 예측은 5초가 소요 되었다. 따라서 학습 모델 로딩 시간을 줄여야 한다.

**Comment by kjlee342** [comment]
@ec209 혹시 두, 세번 연속으로 예측할 때 얼마나 걸리나요?
모델파일을 불러 올 때 오래걸린다면 한 번 로딩해두면 계속 빠르게 쓸 수 있지 않을까요

**Comment by ec209** [comment]
start_time 1525505831.998006
--- 319.7867097854614 seconds ---
180505-164231
[[ 1.46805108 -0.27150142 -0.30625582 -0.36455423  0.7025426  -1.59529805
   1.10678232]]
[0]
start_time2 1525506151.784767
--- 4.6381800174713135 seconds ---
180505-164236
[[ 1.46805108 -0.27150142 -0.30625582 -0.36455423  0.7025426  -1.59529805
   1.10678232]]
[0]
start_time2 1525506156.422989
--- 3.2844111919403076 seconds ---
180505-164239

Process finished with exit code 0

두번 연속 실행시
1차예측 4.6초
2차예측 3.2초 소요됨. 
로딩 해두고 쓴다면 5초 이내에 예측결과를 알 수 있을 듯 합니다.
