### ISSUE TITLE
측정한 데이터를 이용한 예측

### ISSUE THREAD

**Issue by kjlee342** [kookmin-sw/2018-cap1-8#25]
저희가 지난번에 직접 측정한 csi 데이터를 사용하여 제대로 예측이 되는지보고

실험 환경을 논문과 같이 구축해서 다시 측정해야할지 정해야 합니다. 

우선 저희의 데이터를 넣고 확인해주시길 바랍니다.

예측된 값은 [bed, fall, walk, pickup, run, sitdown, standup] 순입니다.

**Comment by bear1704** [comment]
제가 제대로 돌려본 적이 없어서 그런데, Prediction을 위한 소스가 따로 있지 않나요?
만드신거..
있으면 올려주실래요?

**Comment by kjlee342** [comment]
testing 브랜치의 test2.py가 예측 코드입니다.

**Comment by tttuer** [comment]
저희 저번에 행동 측정했던 파일 어디에 보관해 놓았나요? @bear1704

**Comment by bear1704** [comment]
@kjlee342 
측정결과입니다.
측정을 위해 사용한 모델 데이터는 예전에 이틀 걸려서 만든 오리지널 모델과(예전 데이터 사용한)
제가 노트북으로 1.5일동안 돌린 모델(이후에 제작자가 올린 Stanford_ 데이터를 사용한)을 사용하였습니다.

데이터는 저희가 이전에 코딩스튜디오에서 측정한 walk,Run,Stand(가만히 서 있기) 데이터를 사용하였습니다. 

측정결과
stanford 모델 사용 : 
직접측정 (walk) : Run으로 인식.
직접측정 (Run) : Run으로 인식.
직접측정(STAND - 가만히있기 ) :; Run으로 인식.

Original 모델 사용:
직접측정(Stand-가만히있기) : Run으로 인식
직접측정(walk) : Run으로 인식
직접측정(run) : Run으로 인식

참고로 Stand는 Standup이 아니라 그냥 가만히 서 있는 겁니다.

네. 모두 Run으로 인식합니다.  분류(class) 1x7배열의 수치는 각각 다르지만, 결과적으로
모두 Run을 가리켰습니다.
제 생각엔 input으로 뭘 먹였냐에 따라 인식률, 오차율에 현저한 차이를 보이는 것 같습니다.

그 근거로, 오리지널 모델로 새로운 input데이터(Stanford)를 돌려 봤는데, 오차율이 현저히 높았습니다.
그래서 제가 해당 데이터로 새로운 모델을 만들어서 같은 input 데이터를 돌려 본 결과, 
3번 돌렸을 때 3번 정답이 나왔습니다.

아마 인풋데이터도 우리가 만들어야 할 것 같네요..

**Comment by bear1704** [comment]
특히 새롭게 만든 모델은 노트북 연산능력 한계로(..) 원래 10번 반복해야 할 학습을
2번만 하도록 조정하였는데도 이런 결과가 나온 걸 보면, 제공된 데이터를 사용하는건 
정확도에 큰 문제를 일으킬 것 같네요.
