### ISSUE TITLE
캡스톤 책자 작성

### ISSUE THREAD

**Issue by kjlee342** [kookmin-sw/2018-cap1-8#26]
최종발표회에 사용할 책자를 작성해야합니다.

대략적인 양식은 아래와 같으며 양식을 따르지 않아도 사이즈만 같으면 될 것 같습니다.

기한은 2018/ 05 / 28 오후 4:00까지 입니다.

(2) 책자 
 - 판넬에 넣은 내용을 기본으로 추가적으로 작성하고 싶은 내용도 넣어주세요.
 - 판넬과 내용을 똑같아도 무관합니다. 단, 각 팀당 2면씩 들어갈 예정이므로 내용 배치는 적절하게 해주세요. 

[2018 캡스톤 책자 양식(팀번호).pptx](https://github.com/kookmin-sw/2018-cap1-8/files/1990476/2018.pptx)

**Comment by tttuer** [comment]
작성 완료
