### ISSUE TITLE
캡스톤 판넬 작성

### ISSUE THREAD

**Issue by kjlee342** [kookmin-sw/2018-cap1-8#27]
최종발표회에 사용할 판넬을 작성해야합니다.

대략적인 양식은 아래와 같으며 양식을 따르지 않아도 사이즈만 같으면 될 것 같습니다.

기한은 2018/ 05 / 28 오후 4:00까지 입니다.

(1) 판넬
 - A1사이즈로 제작할 예정입니다. 크기를 꼭!!!! 지켜주세요.
 - 발표에 필요한 기본적인 내용을 작성해주세요. (판넬에 미처 넣지 못한 내용은 책자에 넣어 평가 시 참고될 수 있도록 해주세요.)
 - jpg파일로 보낼 경우, 깨져서 출력될 수 있으므로 해상도가 높은 원본파일로 보내주세요.
 - 판넬에 들어가는 이미지는 원본도 함께 보내주세요.

[2018 캡스톤 판넬 양식(팀번호).pptx](https://github.com/kookmin-sw/2018-cap1-8/files/1990492/2018.pptx)

**Comment by tttuer** [comment]
구상 끝

**Comment by tttuer** [comment]
판넬 doc에 업로드
