### ISSUE TITLE
계획서 수정

### ISSUE THREAD

**Issue by kjlee342** [kookmin-sw/2018-cap1-8#3]
수행 계획서 수정

수행 계획서 코멘트
1. Wi-Fi를 이용 침입자 등을 감시. 하지만 침입자 등이 Wi-Fi에 접속되어 있는 모바일 디바이스를 가지고 있어야 함.
2. 학습이 되지 않는 사람이 동일한 동작을 해도 측정이 가능한지?
3. 분류된 동작을 홈IOT에 어떤 방식으로 활용할 것인지 예를 더 구체적으로 알려주세요.
4. 1장에서 WiFI CSI 에 대한 개념을 조금 더 자세히 설명해주는게 좋을것 같습니다.
유사한 연구 논문이 최근에 많이 발표된것으로 압니다. 이에 대한 조사를 실시후, 해당 과제에서 구현하고자 하는 기술의 차이점이 있는지, 아니면 발표된 기술의 내용을 활용해서 구현해 보는 것이 목적인지 작성하면 좋을듯 합니다.
5. 본 프로젝트를 통하여 인식할 사람의 행동이 무엇인지를 정의하길 바랍니다. 문제 정의와 시스템이 반영할 model 이 무엇인지 명확하지 않습니다. 아직 계획을 구체적으로 잡고 있지 않은 것 같습니다. Use Case Diagram 의 오류가 있읍니다. 표준 spec 을 보면서 다시 그려주세요. 본 프로젝트의 주요 서비스는 행동의 인지 부분이지 통신 부분이 아닙니다. 통신부분은 기술 내용으로 넣어주세요.

수행 계획서
https://docs.google.com/document/d/17sslpYfRn9XKDZhVvKvxXdTeDJrAeZqSHx4CKD2S8Ms/edit?usp=sharing

내용 작성 후 다운받아 깨지는 양식을 수정하여 올려주세요

**Comment by tttuer** [comment]
1장에서 WIFI CSI에 대한 개념 추가

**Comment by tttuer** [comment]
1번에 대한 질문은 저희의 설명이 부족했던거 같습니다. 나중에 이 질문을 따로 ppt에서 설명을 하는 것이 좋겠습니다.

**Comment by bear1704** [comment]
유즈케이스와 유즈케이스 다이어그램 관련 내용 개선
