### ISSUE TITLE
예측 방법 수정 방안

### ISSUE THREAD

**Issue by tttuer** [kookmin-sw/2018-cap1-8#34]
예측을 할 때 현재처럼 수동으로 500개씩 짤라서 하는 방법이 아닌 컴퓨터를 이용해서 데이터를 한번에 받고 그 데이터를 500개씩 짤라가면서 비교해 보는 방법을 해봐도 괜찮을 것 같습니다.

**Comment by bear1704** [comment]
새 측정 방안 건의

1. 딜레이를 길게 
2. 측정 시간을 줄여서(2~3초)
3. 집어넣는 y_step을 늘인다(어려움)
4. annotation을 명확하게 (정밀하게)

**Comment by bear1704** [comment]
회의를 통해서 결과를 도출했음
