### ISSUE TITLE
더 빠른 학습, 실시간 연산을 위해 Tensor-gpu(CUDA) 사용을 건의합니다.

### ISSUE THREAD

**Issue by bear1704** [kookmin-sw/2018-cap1-8#35]
저번에 보여주신 1070 그거 써볼까요?

**Comment by kjlee342** [comment]
예측, 학습 속도를 높이기 위해서 가능한 사용하는게 좋을 것 같네요

**Comment by bear1704** [comment]
https://www.nvidia.com/en-us/data-center/gpu-accelerated-applications/tensorflow/

https://developer.nvidia.com/rdp/cudnn-archive

**Comment by kjlee342** [comment]
쿠다 적용 완료
