### ISSUE TITLE
캡스톤 미팅 결과

### ISSUE THREAD

**Issue by kjlee342** [kookmin-sw/2018-cap1-8#36]
1. 행동 수정
handup을 standup으로 변경해야 함.

2. 학습 장소 선택
a. 연구실에서 데이터를 측정하여 제한된 환경에서 적중률을 높이고
시연 때는 말로 설명.
b. 가능한 자율주행 스튜디오에서 사람이 많을 때 데이터를 측정하여 
시연 때 적중률을 최대한 높임.
c. 반반

**Comment by bear1704** [comment]
다른건 몰라도 자율주행에서 하는게 무조건 필요할거라 봅니다.
그리고 최대한 빨리 과사에서 위치 우선권을 받아야 하지 않을까...싶네요

**Comment by ec209** [comment]
교수님 미팅 결과 저희가 인용한 논문 에서는 handup을 학습-예측 시키지 않았고, 교수님 말씀에 그런 hand - gesture recognition 쪽은 다른 분야 라고 하셔서, class중 하나를 standup으로 바꾸는게 타당한것 같습니다
