### ISSUE TITLE
매트랩 코드들과 파이썬 코드 통합

### ISSUE THREAD

**Issue by kjlee342** [kookmin-sw/2018-cap1-8#37]
실시간 예측과 그래프를 보여주기 위해 매트랩 코드와 파이썬 코드 통합 필요

**Comment by tttuer** [comment]
https://kr.mathworks.com/help/matlab/matlab_external/call-matlab-functions-from-python.html
http://yochin47.blogspot.kr/2017/05/python-matlab.html

script 및 function call하기
user defined script/function의 경우는
eng.addpath('path', nargout=0)으로 경로 추가 후,
eng.script_name('nargout=0') 로 스크립트를 실행시키고
eng.func(a, b)로 함수를 실행시키면 됨.
스크립트를 실행시키면 생성된 변수들은 eng.workspace에 다 저장되어 추후에 사용가능.

**Comment by tttuer** [comment]
http://kr.mathworks.com/help/matlab/matlab_external/install-the-matlab-engine-for-python.html

python에서 matlab 실행시키기 위해 하는 첫번째 단계

**Comment by bear1704** [comment]
https://gist.github.com/dangom/303879ca649f7a3fe113912d7ffa62d4

python 3.6으로 매트랩 연동

**Comment by kjlee342** [comment]
매트랩 2017b 버전부터는 3.6을 정상적으로 지원한다고 합니다...

**Comment by tttuer** [comment]
linux 환경에서 Matlab.engine을 사용하는 방법은
.conda/envs/ 여기서 파이선 버젼에 맞는 폴더에 들어가 site-packages에 Matlab engine을 설치할 때 생겨난 파일을 옮기면 됩니다
