### ISSUE TITLE
팀별 사이트 수정

### ISSUE THREAD

**Issue by kjlee342** [kookmin-sw/2018-cap1-8#4]
팀별 사이트 내용 수정 필요

팀 소개
제대로 된 목표 및 설명
영문 요약
팀원 소개

**Comment by tttuer** [comment]
팀 소개 보완, abstract 추가

**Comment by tttuer** [comment]
팀원 소개란에 e-mail란 추가

**Comment by kjlee342** [comment]
프로잭트 오타났어요

**Comment by tttuer** [comment]
그림 추가 완료, 프로잭트 -> 프로젝트 수정

**Comment by kjlee342** [comment]
제 이메일에 유튜브 태그가 달려있어요

**Comment by tttuer** [comment]
유튜브 태그 없이기 수정 완료
